/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package languageapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static languageapp.loginWithRegistry.storeEmail;
import static languageapp.loginWithRegistry.storeFname;
import static languageapp.loginWithRegistry.storeSname;


/**
 *
 * @author Yamin Ullah - w1787623
 */
public class progressPage extends javax.swing.JPanel {
    
    
    
    

    /**
     * Creates new form scenariosPage
     */
    public progressPage() {
        initComponents();
        JFrame frame = new JFrame();        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressLabel = new java.awt.Label();
        inProgressPanel = new javax.swing.JPanel();
        inProgressTitle = new java.awt.Label();
        inProgressNum = new javax.swing.JLabel();
        completedActivityPanel = new javax.swing.JPanel();
        completedActivityLabel = new java.awt.Label();
        completedActiv = new javax.swing.JLabel();
        smallLogoPicture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profilePageButtonMenu = new javax.swing.JButton();
        supportPageMenuButton = new javax.swing.JButton();
        adminRecordButton = new javax.swing.JButton();
        scenariosPageButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 181, 204));

        progressLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        progressLabel.setText("Progress");

        inProgressPanel.setBackground(new java.awt.Color(240, 240, 255));
        inProgressPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inProgressTitle.setText("In Progress");

        inProgressNum.setText("jLabel1");

        javax.swing.GroupLayout inProgressPanelLayout = new javax.swing.GroupLayout(inProgressPanel);
        inProgressPanel.setLayout(inProgressPanelLayout);
        inProgressPanelLayout.setHorizontalGroup(
            inProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inProgressPanelLayout.createSequentialGroup()
                .addGroup(inProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inProgressPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(inProgressNum))
                    .addGroup(inProgressPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(inProgressTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        inProgressPanelLayout.setVerticalGroup(
            inProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inProgressPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(inProgressNum)
                .addGap(21, 21, 21)
                .addComponent(inProgressTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        inProgressTitle.getAccessibleContext().setAccessibleName("In Progress");

        completedActivityPanel.setBackground(new java.awt.Color(240, 240, 255));
        completedActivityPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        completedActivityLabel.setText("Completed Activity");

        completedActiv.setText("jLabel1");

        javax.swing.GroupLayout completedActivityPanelLayout = new javax.swing.GroupLayout(completedActivityPanel);
        completedActivityPanel.setLayout(completedActivityPanelLayout);
        completedActivityPanelLayout.setHorizontalGroup(
            completedActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedActivityPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(completedActiv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completedActivityPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(completedActivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        completedActivityPanelLayout.setVerticalGroup(
            completedActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completedActivityPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(completedActiv)
                .addGap(25, 25, 25)
                .addComponent(completedActivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        completedActivityLabel.getAccessibleContext().setAccessibleName("");
        completedActivityLabel.getAccessibleContext().setAccessibleParent(null);

        smallLogoPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/earth-globeprofile-page.png"))); // NOI18N
        smallLogoPicture.setText("\n");
        smallLogoPicture.setToolTipText("");

        profilePageButtonMenu.setText("Profile Page");
        profilePageButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePageButtonMenuActionPerformed(evt);
            }
        });

        supportPageMenuButton.setText("Support Page");
        supportPageMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportPageMenuButtonActionPerformed(evt);
            }
        });

        adminRecordButton.setText("Admin Records");
        adminRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRecordButtonActionPerformed(evt);
            }
        });

        scenariosPageButton.setText("Scenarios");
        scenariosPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scenariosPageButtonActionPerformed(evt);
            }
        });

        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signOutButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(profilePageButtonMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supportPageMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(smallLogoPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scenariosPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(inProgressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(completedActivityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(smallLogoPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inProgressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(completedActivityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(profilePageButtonMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminRecordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scenariosPageButton)
                        .addGap(18, 18, 18)
                        .addComponent(supportPageMenuButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(signOutButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profilePageButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePageButtonMenuActionPerformed
        // TODO add your handling code here:
        //Takes you to the Profile page, this is aport of the menu buttons which all pages have.
        profilePage emp = new profilePage();
        emp.setVisible(true);
        setVisible(false); //Closes This window
        
    }//GEN-LAST:event_profilePageButtonMenuActionPerformed

    private void supportPageMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportPageMenuButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the Support page, this is aport of the menu buttons which all pages have.
        // As the suuport page has not been implemented in to the project this section has been commented out
        // supportPage emp = new suuportPage();
        //emp.setVisible(true);
        //setVisible(false); //Closes This window
    }//GEN-LAST:event_supportPageMenuButtonActionPerformed

    private void adminRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRecordButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the profile page
        teacherPage emp = new teacherPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window        // TODO add your handling code here:

    }//GEN-LAST:event_adminRecordButtonActionPerformed

    private void scenariosPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scenariosPageButtonActionPerformed
        // TODO add your handling code here:
        ScenarioPage emp = new ScenarioPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window
        
    }//GEN-LAST:event_scenariosPageButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the SIGNOUT page
        loginWithRegistry emp = new loginWithRegistry();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_signOutButtonActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminRecordButton;
    private javax.swing.JLabel completedActiv;
    private java.awt.Label completedActivityLabel;
    private javax.swing.JPanel completedActivityPanel;
    private javax.swing.JLabel inProgressNum;
    private javax.swing.JPanel inProgressPanel;
    private java.awt.Label inProgressTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton profilePageButtonMenu;
    private java.awt.Label progressLabel;
    private javax.swing.JButton scenariosPageButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel smallLogoPicture;
    private javax.swing.JButton supportPageMenuButton;
    // End of variables declaration//GEN-END:variables
}



