/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LevelA1;

import LevelA1.CrossCulturalExperiences.LevelA1InternationalFood;
import LevelA1.Directions.LevelA1DeliveryDriver;
import LevelA1.Employment.LevelA1Cover;
import LevelA1.ExchangingPersonalInfo.LevelA1DescriptionOfTown;
import LevelA1.ExchangingPersonalInfo.LevelA1Instagram;
import LevelA1.ExchangingPersonalInfo.LevelA1Neighbour;
import LevelA1.ExchangingPersonalInfo.LevelA1SocialMedia;
import LevelA1.Introductions.LevelA1RepeatName;
import LevelA1.Invitations.LevelA1ChildBirthday;
import LevelA1.Invitations.LevelA1DisneyLand;
import LevelA1.MakingAppointments.LevelA1Booking;
import LevelA1.MakingAppointments.LevelA1SpellingName;
import LevelA1.Ordering.LevelA1CocktailsByCard;
import LevelA1.Ordering.LevelA1CoffeeOrder;
import LevelA1.Ordering.LevelA1Reservation;
import LevelA1.Ordering.LevelA1Takeaway;
import LevelA1.Ordering.LevelA1WaterforTable;
import LevelA1.Shopping.LevelA1Payment;
import LevelA1.Shopping.LevelA1Refund;
import LevelA1.Socialising.LevelA1Interviewarrangements;
import LevelA1.UniversityLife.LevelA1CafeStudy;
import LevelA2.LevelA2Page;
import LevelB1.LevelB1Page;
import LevelB2.LevelB2Page;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import languageapp.LanguagePage;
import languageapp.ScenarioPage;
import languageapp.loginWithRegistry;
import languageapp.profilePage;
import languageapp.progPage;
import languageapp.supportPage;
import languageapp.teacherPage;


/**
 *
 * @author w1740779 - omar
 */
public class LevelA1Page extends javax.swing.JFrame {
    //stores subcombo data //subcombo stores the subcontext opions in the context and links them toether
    HashMap <String, String[]> subcombo = new HashMap <String, String[]>();
    String[] contexts = {"Ordering food and drink", "Exchanging personal information",
    "Making Appointments", "Going shopping and asking for prices", "Introductions", "Basic employment issues", "Making invitations", "Socialising in the country", "Asking and giving directions", "University life", "Cross-cultural experiences"};
    
    String[] foodanddrinkOptions = {"Takeaway", "Coffee Order", "Reservation", "Cocktails by card payment", "Water for table"};
    String[] personalinformationOptions = {"Social Media", "Instagram", "Neighbours parcel", "Description of of town"};
    String[] appointmentsOptions = {"Booking", "Spelling your name"};
    String[] shoppingpricesOptions = {"Payment", "Refund"};
    String[] introductionsOptions = {"Repeat name"};
    String[] employmentOptions = {"Cover", "Interview"};
    String[] invitationsOptions = {"Disneyland", "Help with child's birthday party"};
    String[] socialisingOptions = {"Interview arrangements"};
    String[] directionsOptions = {"Delivery driver"};
    String[] unilifeOptions = {"Study in cafe"};
    String[] crosscultureOptions = {"International food"};
    
    
    
    /**
     * Creates new form profilePage
     */

    public LevelA1Page() {
        initComponents();
//        jComboBox_Context.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton_profile = new javax.swing.JButton();
        jLabelPic1 = new javax.swing.JLabel();
        jButton_Scenario = new javax.swing.JButton();
        jButton_SignOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_B2 = new javax.swing.JButton();
        jButton_A2 = new javax.swing.JButton();
        jButton_B1 = new javax.swing.JButton();
        jButton_ProgPage = new javax.swing.JButton();
        jButton_Languages = new javax.swing.JButton();
        jButton_SupportPage2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_LevelA1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton_Submit = new javax.swing.JButton();
        jComboBox_SubContext = new javax.swing.JComboBox<>();
        //allows me to put the relevant context topic with the subcontext
        subcombo.put(contexts[0], foodanddrinkOptions);
        subcombo.put(contexts[1], personalinformationOptions);
        subcombo.put(contexts[2], appointmentsOptions);
        subcombo.put(contexts[3], shoppingpricesOptions);
        subcombo.put(contexts[4], introductionsOptions);
        subcombo.put(contexts[5], employmentOptions);
        subcombo.put(contexts[6], invitationsOptions);
        subcombo.put(contexts[7], socialisingOptions);
        subcombo.put(contexts[8], directionsOptions);
        subcombo.put(contexts[9], unilifeOptions);
        subcombo.put(contexts[10], crosscultureOptions);
        jComboBox_Context = new javax.swing.JComboBox<>(contexts);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanuage App");
        setMinimumSize(new java.awt.Dimension(930, 530));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 181, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_profile.setText("Profile");
        jButton_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_profileActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 41));
        jPanel4.add(jLabelPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 34, -1, 112));

        jButton_Scenario.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Scenario.setText("Scenario");
        jButton_Scenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ScenarioActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Scenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 41));

        jButton_SignOut.setText("Sign Out");
        jButton_SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignOutActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Language Exchange");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/earth-globeprofile-page.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jButton_B2.setText("B2");
        jButton_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 50, -1));

        jButton_A2.setText("A2");
        jButton_A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_A2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, -1));

        jButton_B1.setText("B1");
        jButton_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, -1));

        jButton_ProgPage.setText("Progress Page");
        jButton_ProgPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProgPageActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_ProgPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, 41));

        jButton_Languages.setText("Languages");
        jButton_Languages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LanguagesActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Languages, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, -1, -1));

        jButton_SupportPage2.setText("Support Page");
        jButton_SupportPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupportPage2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_SupportPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, 41));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 760));

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 181, 204));
        jLabel5.setText("Choose which topic you want to practice:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jPanel_LevelA1.setBackground(new java.awt.Color(0, 181, 204));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LEVEL A1");

        javax.swing.GroupLayout jPanel_LevelA1Layout = new javax.swing.GroupLayout(jPanel_LevelA1);
        jPanel_LevelA1.setLayout(jPanel_LevelA1Layout);
        jPanel_LevelA1Layout.setHorizontalGroup(
            jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_LevelA1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_LevelA1Layout.setVerticalGroup(
            jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_LevelA1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel_LevelA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jButton_Submit.setText("Submit");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jComboBox_SubContext.setEditable(true);
        jComboBox_SubContext.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox_SubContext.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_SubContext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SubContextActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_SubContext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 210, -1));

        jComboBox_Context.setEditable(true);
        jComboBox_Context.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox_Context.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_Context.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ContextActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Context, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 210, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 740));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1100, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1316, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_profileActionPerformed
       //Takes you to the Profile page
        profilePage emp = new profilePage();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_profileActionPerformed

    private void jButton_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B2ActionPerformed
        //Takes you to the A2 Page
        LevelB2Page emp = new LevelB2Page();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_B2ActionPerformed

    private void jButton_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_A2ActionPerformed
         //Takes you to the A2 Page
        LevelA2Page emp = new LevelA2Page();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_A2ActionPerformed

    private void jButton_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B1ActionPerformed
        //Takes you to the B1 Page
        LevelB1Page emp = new LevelB1Page();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_B1ActionPerformed

    private void jButton_SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignOutActionPerformed
        //Takes you to the login page
        loginWithRegistry emp = new loginWithRegistry();
        emp.setVisible(true);
        setVisible(false); //Closes This window // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SignOutActionPerformed

    private void jButton_ScenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ScenarioActionPerformed
        //Takes you to the scenario page
        ScenarioPage emp = new ScenarioPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ScenarioActionPerformed

    private void jComboBox_SubContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SubContextActionPerformed
       
    }//GEN-LAST:event_jComboBox_SubContextActionPerformed

    private void jComboBox_ContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ContextActionPerformed
         //the item selected by the user is turned into a string      
        String item = (String)jComboBox_Context.getSelectedItem();
        //allows you me to return 1-based position from where the item is on the stack
            Object o = subcombo.get(item);

            if (o == null) {
                //if its null it constructs an empty Combobox
                jComboBox_SubContext.setModel(new DefaultComboBoxModel());
            }
            else {
                //if its not null it the vaulues in the subcontext options appear in the jcombo box
                jComboBox_SubContext.setModel(new DefaultComboBoxModel((String[])o));
            }
    }//GEN-LAST:event_jComboBox_ContextActionPerformed
        
    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
                //opt 1 puts any seleceted item by the user into a string
                String opt1 = (String) jComboBox_Context.getSelectedItem();
                //opt 2 puts any seleceted item by the user into a string
                String opt2 = (String)  jComboBox_SubContext.getSelectedItem();
                

                    

//Compares the selected items and takes the user to the relevant page
        
//food and drink section 
        
        if (opt1.equals(contexts[0])  && opt2.equals(foodanddrinkOptions[0])){ 
         LevelA1Takeaway();
        }
        else if (opt1.equals(contexts[0])  && opt2.equals(foodanddrinkOptions[1])){ 
         LevelA1CoffeeOrder(); 
        }
        else if (opt1.equals(contexts[0])  && opt2.equals(foodanddrinkOptions[2])){ 
        LevelA1Reservation();
        }
        else if (opt1.equals(contexts[0])  && opt2.equals(foodanddrinkOptions[3])){ 
        LevelA1CocktailsByCard();  
        }  
        else if (opt1.equals(contexts[0])  && opt2.equals(foodanddrinkOptions[4])){ 
        LevelA1WaterforTable();
        }
       
        
    
//       
//personal information section
        else if (opt1.equals(contexts[1])  && opt2.equals(personalinformationOptions[0])){ 
            LevelA1SocialMedia();
        }
        else if (opt1.equals(contexts[1])  && opt2.equals(personalinformationOptions[1])){ 
         LevelA1Instagram(); 
        }
        else if (opt1.equals(contexts[1])  && opt2.equals(personalinformationOptions[2])){ 
        LevelA1Neighbour();
        }
        else if (opt1.equals(contexts[1])  && opt2.equals(personalinformationOptions[3])){ 
        LevelA1DescriptionOfTown();  
        } 
//
//Making appointments
        else if (opt1.equals(contexts[2])  && opt2.equals(appointmentsOptions[0])){ 
            LevelA1Booking();
        }
        else if (opt1.equals(contexts[2])  && opt2.equals(appointmentsOptions[1])){ 
         LevelA1SpellingName(); 
        }
//
//Going shopping and asking for prices
        
        else if (opt1.equals(contexts[3])  && opt2.equals(shoppingpricesOptions[0])){ 
            LevelA1Payment();
        }
        else if (opt1.equals(contexts[3])  && opt2.equals(shoppingpricesOptions[1])){ 
         LevelA1Refund(); 
        }
//        
//  Introductions
        else if (opt1.equals(contexts[4])  && opt2.equals(introductionsOptions[0])){ 
            LevelA1RepeatName();
        }
//
//  Basic employment issues
        else if (opt1.equals(contexts[5])  && opt2.equals(employmentOptions[0])){ 
            LevelA1Cover();
        }
        else if (opt1.equals(contexts[5])  && opt2.equals(employmentOptions[1])){ 
            LevelA1Interview();
        }
//
//Making invitations        
          else if (opt1.equals(contexts[6])  && opt2.equals(invitationsOptions[0])){ 
            LevelA1DisneyLand();
        }
        else if (opt1.equals(contexts[6])  && opt2.equals(invitationsOptions[1])){ 
            LevelA1ChildBirthday();
        } 
 //
 //Socialising in the country
        else if (opt1.equals(contexts[7])  && opt2.equals(socialisingOptions[0])){ 
            LevelA1Interviewarrangements();
        } 
//
//Asking and giving directions
        else if (opt1.equals(contexts[8])  && opt2.equals(directionsOptions[0])){ 
            LevelA1DeliveryDriver();
        }
 //
 //univerity life
         else if (opt1.equals(contexts[9])  && opt2.equals(unilifeOptions[0])){ 
            LevelA1CafeStudy();
        }
        //univerity life
         else if (opt1.equals(contexts[10])  && opt2.equals(crosscultureOptions[0])){ 
            LevelA1InternationalFood();
        }
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jButton_ProgPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProgPageActionPerformed
        //Takes you to the profile page
        progPage emp = new progPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ProgPageActionPerformed

    private void jButton_LanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LanguagesActionPerformed
        //Takes you to the languagepage
        LanguagePage emp = new LanguagePage();
        emp.setVisible(true);
        setVisible(false); //Closes This window // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LanguagesActionPerformed

    private void jButton_SupportPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupportPage2ActionPerformed

        supportPage emp = new supportPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_SupportPage2ActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelA1Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelA1Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelA1Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelA1Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelA1Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_A2;
    private javax.swing.JButton jButton_B1;
    private javax.swing.JButton jButton_B2;
    private javax.swing.JButton jButton_Languages;
    private javax.swing.JButton jButton_ProgPage;
    private javax.swing.JButton jButton_Scenario;
    private javax.swing.JButton jButton_SignOut;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JButton jButton_SupportPage;
    private javax.swing.JButton jButton_SupportPage1;
    private javax.swing.JButton jButton_SupportPage2;
    private javax.swing.JButton jButton_SupportPage3;
    private javax.swing.JButton jButton_profile;
    private javax.swing.JComboBox<String> jComboBox_Context;
    private javax.swing.JComboBox<String> jComboBox_SubContext;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPic1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_LevelA1;
    // End of variables declaration//GEN-END:variables

    
    //Takes you to the LevelA1TakeawayPage 
    private void LevelA1Takeaway() {
        LevelA1Takeaway emp = new LevelA1Takeaway();
        emp.setVisible(true);
        setVisible(false); //Closes This window 
    }
    
    //Takes you to the LevelA1CoffeeOrder page
    private void LevelA1CoffeeOrder() {
          LevelA1CoffeeOrder emp = new LevelA1CoffeeOrder();
          emp.setVisible(true);
          setVisible(false); //Closes This window 
    }
//Takes you to the LevelA1WaterforTable page
    private void LevelA1WaterforTable() {
        LevelA1WaterforTable emp = new LevelA1WaterforTable();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Reservation page
    private void LevelA1Reservation() {
        LevelA1Reservation emp = new LevelA1Reservation();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1CocktailsByCard page
    private void LevelA1CocktailsByCard() {
         LevelA1CocktailsByCard emp = new LevelA1CocktailsByCard();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1SocialMedia page
    private void LevelA1SocialMedia() {
        LevelA1SocialMedia emp = new LevelA1SocialMedia();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Instagram page
    private void LevelA1Instagram() {
         LevelA1Instagram emp = new LevelA1Instagram();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Neighbour page
    private void LevelA1Neighbour() {
   LevelA1Neighbour emp = new LevelA1Neighbour();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
        }
//Takes you to the LevelA1DescriptionOfTown page
    private void LevelA1DescriptionOfTown() {
    LevelA1DescriptionOfTown emp = new LevelA1DescriptionOfTown();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Booking page
    private void LevelA1Booking() {
        LevelA1Booking emp = new LevelA1Booking();
        emp.setVisible(true);
        setVisible(false); //Closes This window 
    }
//Takes you to the LevelA1SpellingName page
    private void LevelA1SpellingName() {
        LevelA1SpellingName emp = new LevelA1SpellingName();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Payment page
    private void LevelA1Payment() {
  LevelA1Payment emp = new LevelA1Payment();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Refund page
    private void LevelA1Refund() {
        LevelA1Refund emp = new LevelA1Refund();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1RepeatName page
    private void LevelA1RepeatName() {
        LevelA1RepeatName emp = new LevelA1RepeatName();
        emp.setVisible(true);
        setVisible(false); //Closes This window 
    }
//Takes you to the LevelA1Cover page
    private void LevelA1Cover() {
   LevelA1Cover emp = new LevelA1Cover();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1Interview  page
    private void LevelA1Interview() {
    LevelA1Interviewarrangements emp = new LevelA1Interviewarrangements();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1DisneyLand page
    private void LevelA1DisneyLand() {
   LevelA1DisneyLand emp = new LevelA1DisneyLand();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
}  
    //Takes you to the LevelA1ChildBirthday page
    private void LevelA1ChildBirthday() {
        LevelA1ChildBirthday emp = new LevelA1ChildBirthday();
        emp.setVisible(true);
        setVisible(false); //Closes This window 
}  
//Takes you to the LevelA1Interviewarrangements page
    private void LevelA1Interviewarrangements() {
  LevelA1Interviewarrangements emp = new LevelA1Interviewarrangements();
        emp.setVisible(true);
        setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1DeliveryDriver pagepage
    private void LevelA1DeliveryDriver() {
    LevelA1DeliveryDriver emp = new LevelA1DeliveryDriver();
        emp.setVisible(true);
        setVisible(false); //Closes This window 
    }
//Takes you to the LevelA1CafeStudy page
    private void LevelA1CafeStudy() {
  LevelA1CafeStudy emp = new LevelA1CafeStudy();
       emp.setVisible(true);
       setVisible(false); //Closes This window  
    }
//Takes you to the LevelA1InternationalFood page
    private void LevelA1InternationalFood() {
    LevelA1InternationalFood emp = new LevelA1InternationalFood();
       emp.setVisible(true);
       setVisible(false); //Closes This window 
    }
    }