/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LevelA2;



import LevelA1.LevelA1Page;
import LevelA2.Weather.*;
import LevelB1.LevelB1Page;
import LevelB2.LevelB2Page;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import languageapp.LanguagePage;
import languageapp.ScenarioPage;
import languageapp.loginWithRegistry;
import languageapp.profilePage;
import languageapp.progPage;
import languageapp.supportPage;
import languageapp.teacherPage;


/**
 *
 * @author  w1740779 - omar
 */
public class LevelA2Page extends javax.swing.JFrame {
    //stores subcombo data //subcombo stores the subcontext opions in the context and links them toether
    HashMap <String, String[]> subcombo = new HashMap <String, String[]>();
    String[] contexts = {"Introductions", "Making Appointments", "Asking and giving directions","Making invitations", "Ordering food and drink", "Going shopping and asking for prices", "Health matters"
            , "Socialising in the country", "Making travel arrangements","Exchanging personal information", "Cross-cultural experiences",  "Weather and weather conditions"}; 
    
    String[] introOptions = {"Ist day in job", "Job offer"};
    String[] appointmentsOptions = {"Dentist", "Doctor"};
    String[] givedirectionsOptions = {"Hospital Visit", "Delivery Driver"};
    String[] invitationsOptions = {"Lunch", "Charity", "Children at wedding", "Wedding RSVP"};
    String[] orderfoodOptions = {"Delayed drink order", "QR code", "Cocktails(1)", "Cocktails(2)", "Vegan pizza", "Reservation"};
    String[] shoppingpricesOptions = {"Payment"};
    String[] hmOptions = {"Sick relative", "Visiting patient"};
    String[] socialisingOptions = {"Family size", "Hobbies"};
    String[] travelOptions = {"Expired ticket"};
    String[] personalInfOptions = {"Age restricted"};
    String[] cultureOptions = {"Omelette"};
    String[] weatherOptions = {"Clothing for weather"};
        

    
    /**
     * Creates new form profilePage
     */

    public LevelA2Page() {
        initComponents();
//        jComboBox_Context.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton_profile = new javax.swing.JButton();
        jLabelPic1 = new javax.swing.JLabel();
        jButton_Scenario = new javax.swing.JButton();
        jButton_SignOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_A1 = new javax.swing.JButton();
        jButton_B1 = new javax.swing.JButton();
        jButton_B2 = new javax.swing.JButton();
        jButton_Languages = new javax.swing.JButton();
        jButton_ProgPage = new javax.swing.JButton();
        jButton_SupportPage = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_LevelA1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton_Submit = new javax.swing.JButton();
        jComboBox_SubContext = new javax.swing.JComboBox<>();
        //allows me to put the relevant context topic with the subcontext
        subcombo.put(contexts[0], introOptions);
        subcombo.put(contexts[1], appointmentsOptions);
        subcombo.put(contexts[2], givedirectionsOptions);
        subcombo.put(contexts[3], invitationsOptions);
        subcombo.put(contexts[4], orderfoodOptions);
        subcombo.put(contexts[5], shoppingpricesOptions);
        subcombo.put(contexts[6], hmOptions);
        subcombo.put(contexts[7], socialisingOptions);
        subcombo.put(contexts[8], travelOptions);
        subcombo.put(contexts[9], personalInfOptions);
        subcombo.put(contexts[10], cultureOptions);
        subcombo.put(contexts[11], weatherOptions);
        jComboBox_Context = new javax.swing.JComboBox<>(contexts);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanuage App");
        setMinimumSize(new java.awt.Dimension(930, 530));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 181, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_profile.setText("Profile");
        jButton_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_profileActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 41));
        jPanel4.add(jLabelPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 34, -1, 112));

        jButton_Scenario.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Scenario.setText("Scenario");
        jButton_Scenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ScenarioActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Scenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 41));

        jButton_SignOut.setText("Sign Out");
        jButton_SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignOutActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Language Exchange");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/earth-globeprofile-page.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jButton_A1.setText("A1");
        jButton_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_A1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, -1));

        jButton_B1.setText("B1");
        jButton_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, -1));

        jButton_B2.setText("B2");
        jButton_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 50, -1));

        jButton_Languages.setText("Languages");
        jButton_Languages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LanguagesActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Languages, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, -1, -1));

        jButton_ProgPage.setText("Progress Page");
        jButton_ProgPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProgPageActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_ProgPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, 41));

        jButton_SupportPage.setText("Support Page");
        jButton_SupportPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupportPageActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_SupportPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 110, 41));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 760));

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 181, 204));
        jLabel5.setText("Choose which topic you want to practice:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jPanel_LevelA1.setBackground(new java.awt.Color(0, 181, 204));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LEVEL A2");

        javax.swing.GroupLayout jPanel_LevelA1Layout = new javax.swing.GroupLayout(jPanel_LevelA1);
        jPanel_LevelA1.setLayout(jPanel_LevelA1Layout);
        jPanel_LevelA1Layout.setHorizontalGroup(
            jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_LevelA1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_LevelA1Layout.setVerticalGroup(
            jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_LevelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_LevelA1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel_LevelA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jButton_Submit.setText("Submit");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jComboBox_SubContext.setEditable(true);
        jComboBox_SubContext.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox_SubContext.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_SubContext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SubContextActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_SubContext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 210, -1));

        jComboBox_Context.setEditable(true);
        jComboBox_Context.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox_Context.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_Context.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ContextActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Context, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 210, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 740));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1100, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1316, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_profileActionPerformed
       //Takes you to the Profile page
        profilePage emp = new profilePage();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_profileActionPerformed

    private void jButton_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_A1ActionPerformed
         //Takes you to the A2 Page
        LevelA1Page emp = new LevelA1Page();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_A1ActionPerformed

    private void jButton_SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignOutActionPerformed
        //Takes you to the login page
        loginWithRegistry emp = new loginWithRegistry();
        emp.setVisible(true);
        setVisible(false); //Closes This window // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SignOutActionPerformed

    private void jButton_ScenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ScenarioActionPerformed
        //Takes you to the scenario page
        ScenarioPage emp = new ScenarioPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ScenarioActionPerformed

    private void jComboBox_SubContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SubContextActionPerformed
       
    }//GEN-LAST:event_jComboBox_SubContextActionPerformed

    private void jComboBox_ContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ContextActionPerformed
         //the item selected by the user is turned into a string      
        String item = (String)jComboBox_Context.getSelectedItem();
        //allows you me to return 1-based position from where the item is on the stack
            Object o = subcombo.get(item);

            if (o == null) {
                //if its null it constructs an empty Combobox
                jComboBox_SubContext.setModel(new DefaultComboBoxModel());
            }
            else {
                //if its not null it the vaulues in the subcontext options appear in the jcombo box
                jComboBox_SubContext.setModel(new DefaultComboBoxModel((String[])o));
            }
    }//GEN-LAST:event_jComboBox_ContextActionPerformed
        
    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
                //opt 1 puts any seleceted item by the user into a string
                String opt1 = (String) jComboBox_Context.getSelectedItem();
                //opt 2 puts any seleceted item by the user into a string
                String opt2 = (String)  jComboBox_SubContext.getSelectedItem();
                

                    

//Compares the selected items and takes the user to the relevant page
       
//introduction section 
        
             if (opt1.equals(contexts[0])  && opt2.equals(introOptions[0])){ 
         LevelA21stDayInJob();
        }
        else if (opt1.equals(contexts[0])  && opt2.equals(introOptions[1])){ 
         LevelA2JobOffer();
        }
//       
//Making appointments section 
         else if (opt1.equals(contexts[1])  && opt2.equals(appointmentsOptions[0])){ 
            LevelA2Dentist();
        }
        else if (opt1.equals(contexts[1])  && opt2.equals(appointmentsOptions[1])){ 
            LevelA2Doctor(); 
        } 
        
        
//
//Asing and giving directions section 
        else if (opt1.equals(contexts[2])  && opt2.equals(givedirectionsOptions[0])){ 
            LevelA2HospitalVisit(); 
        }
        else if (opt1.equals(contexts[2])  && opt2.equals(givedirectionsOptions[1])){ 
            LevelA2DeliveryDriver();
        }
//Making invitations   section       
        else if (opt1.equals(contexts[3])  && opt2.equals(invitationsOptions[0])){ 
            LevelA2Lunch();
        }
        else if (opt1.equals(contexts[3])  && opt2.equals(invitationsOptions[1])){ 
         LevelA2Charity(); 
        }
        else if (opt1.equals(contexts[3])  && opt2.equals(invitationsOptions[2])){ 
          LevelA2ChildrenAtWedding();
        }
        else if (opt1.equals(contexts[3])  && opt2.equals(invitationsOptions[3])){ 
         LevelA2WeddingRSVP(); 
        }
//        
//  Ordering food and drinks section 
        else if (opt1.equals(contexts[4])  && opt2.equals(orderfoodOptions[0])){ 
            LevelA2DelayedDrinksOrder();
        }
        else if (opt1.equals(contexts[4])  && opt2.equals(orderfoodOptions[1])){ 
            LevelA2QRCode();
        }
        else if (opt1.equals(contexts[4])  && opt2.equals(orderfoodOptions[2])){ 
            LevelA2Cocktails1();
        }
        else if (opt1.equals(contexts[4])  && opt2.equals(orderfoodOptions[3])){ 
            LevelA2Cocktails2();
        }
        else if (opt1.equals(contexts[4])  && opt2.equals(orderfoodOptions[4])){ 
            LevelA2VeganPizza();
        }
        else if (opt1.equals(contexts[4])  && opt2.equals(orderfoodOptions[5])){ 
            LevelA2Reservation();
        }
//
//  Going shopping and asking for prices section 
        else if (opt1.equals(contexts[5])  && opt2.equals(shoppingpricesOptions[0])){ 
            LevelA2Payment();
        } 
//
//Health matters     section     
        else if (opt1.equals(contexts[6])  && opt2.equals(hmOptions[0])){ 
            LevelA2SickRelative();
        }
        else if (opt1.equals(contexts[6])  && opt2.equals(hmOptions[1])){ 
            LevelA2VisitingPatient();
        } 
//
//Socialising in the country section 
        else if (opt1.equals(contexts[7])  && opt2.equals(socialisingOptions[0])){ 
            LevelA2FamilySize();
        } 
        else if (opt1.equals(contexts[7])  && opt2.equals(socialisingOptions[1])){ 
            LevelA2Hobbies();
        }
//
//Making travel arrangements section 
        else if (opt1.equals(contexts[8])  && opt2.equals(travelOptions[0])){ 
            LevelA2ExpiredTicket();
        }
//
//Exchanging personal information section 
         else if (opt1.equals(contexts[9])  && opt2.equals(personalInfOptions[0])){ 
            LevelA2AgeRestricted();
        }
//         
//Cross-cultural experience section 
         else if (opt1.equals(contexts[10])  && opt2.equals(cultureOptions[0])){ 
            LevelA2Omelette();
        }
 //weather 
         else if (opt1.equals(contexts[10])  && opt2.equals(weatherOptions[0])){ 
            LevelA2Weather();
        }
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jButton_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B1ActionPerformed
        //Takes you to the B1 Page
        LevelB1Page emp = new LevelB1Page();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_B1ActionPerformed

    private void jButton_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B2ActionPerformed
        //Takes you to the A2 Page
        LevelB2Page emp = new LevelB2Page();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_B2ActionPerformed

    private void jButton_LanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LanguagesActionPerformed
        //Takes you to the languagepage
        LanguagePage emp = new LanguagePage();
        emp.setVisible(true);
        setVisible(false); //Closes This window // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LanguagesActionPerformed

    private void jButton_ProgPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProgPageActionPerformed
        //Takes you to the profile page
        progPage emp = new progPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ProgPageActionPerformed

    private void jButton_SupportPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupportPageActionPerformed

        supportPage emp = new supportPage();
        emp.setVisible(true);
        setVisible(false); //Closes This window
    }//GEN-LAST:event_jButton_SupportPageActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelA2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelA2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelA2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelA2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelA2Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_A1;
    private javax.swing.JButton jButton_B1;
    private javax.swing.JButton jButton_B2;
    private javax.swing.JButton jButton_Languages;
    private javax.swing.JButton jButton_ProgPage;
    private javax.swing.JButton jButton_Scenario;
    private javax.swing.JButton jButton_SignOut;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JButton jButton_SupportPage;
    private javax.swing.JButton jButton_profile;
    private javax.swing.JComboBox<String> jComboBox_Context;
    private javax.swing.JComboBox<String> jComboBox_SubContext;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPic1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_LevelA1;
    // End of variables declaration//GEN-END:variables

    
    //Takes you to the LevelA21stDayInJob Page 
    private void LevelA21stDayInJob() {
        LevelA2.Introductions.LevelA21stDayInJob emp = new LevelA2.Introductions.LevelA21stDayInJob();
        emp.setVisible(true);
        setVisible(false); //Closes This window 
    }
    //Takes you to the LevelA2JobOffer page
    private void LevelA2JobOffer() {
          LevelA2.Introductions.LevelA2JobOffer emp = new LevelA2.Introductions.LevelA2JobOffer();
          emp.setVisible(true);
          setVisible(false); //Closes This window 
    }
  //Takes you to the LevelA2Dentist page
    private void LevelA2Dentist() {
       LevelA2.MakingAppointments.LevelA2Dentist emp = new LevelA2.MakingAppointments.LevelA2Dentist();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2Doctor page
    private void LevelA2Doctor() {
      LevelA2.MakingAppointments.LevelA2Doctor emp = new LevelA2.MakingAppointments.LevelA2Doctor();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2DeliveryDriver page
    private void LevelA2DeliveryDriver() {
  LevelA2.AskingAndGivingDirections.LevelA2DeliveryDriver emp = new LevelA2.AskingAndGivingDirections.LevelA2DeliveryDriver();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2HospitalVisit page
    private void LevelA2HospitalVisit() {
        LevelA2.AskingAndGivingDirections.LevelA2HospitalVisit emp = new LevelA2.AskingAndGivingDirections.LevelA2HospitalVisit();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2Lunch page
    private void LevelA2Lunch() {
       LevelA2.MakingInvitations.LevelA2Lunch emp = new LevelA2.MakingInvitations.LevelA2Lunch();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2Charity page
    private void LevelA2Charity() {
 LevelA2.MakingInvitations.LevelA2Charity emp = new LevelA2.MakingInvitations.LevelA2Charity();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2ChildrenAtWedding page
    private void LevelA2ChildrenAtWedding() {
LevelA2.MakingInvitations.LevelA2ChildrenAtWedding emp = new LevelA2.MakingInvitations.LevelA2ChildrenAtWedding();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2WeddingRSVP page
    private void LevelA2WeddingRSVP() {
LevelA2.MakingInvitations.LevelA2WeddingRSVP emp = new LevelA2.MakingInvitations.LevelA2WeddingRSVP();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2DelayedDrinksOrder page
    private void LevelA2DelayedDrinksOrder() {
LevelA2.OrderingFoodAndDrinks.LevelA2DelayedDrinksOrder emp = new LevelA2.OrderingFoodAndDrinks.LevelA2DelayedDrinksOrder();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2QRCode page
    private void LevelA2QRCode() {
        LevelA2.OrderingFoodAndDrinks.LevelA2QRCode emp = new LevelA2.OrderingFoodAndDrinks.LevelA2QRCode();
       emp.setVisible(true);
       setVisible(false); //Closes This window    }
    }
    //Takes you to the LevelA2Cocktails1 page
    private void LevelA2Cocktails1() {
       LevelA2.OrderingFoodAndDrinks.LevelA2Cocktails1 emp = new LevelA2.OrderingFoodAndDrinks.LevelA2Cocktails1();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2Cocktails2 page
    private void LevelA2Cocktails2() {
    LevelA2.OrderingFoodAndDrinks.LevelA2Cocktails2 emp = new LevelA2.OrderingFoodAndDrinks.LevelA2Cocktails2();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
//Takes you to the LevelA2VeganPizza page
    private void LevelA2VeganPizza() {
    LevelA2.OrderingFoodAndDrinks.LevelA2VeganPizza emp = new LevelA2.OrderingFoodAndDrinks.LevelA2VeganPizza();
       emp.setVisible(true);
       setVisible(false); //Closes This window
    }
       private void LevelA2Reservation() {
LevelA2.OrderingFoodAndDrinks.LevelA2Reservation emp = new LevelA2.OrderingFoodAndDrinks.LevelA2Reservation();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2Payment page
    private void LevelA2Payment() {
LevelA2.GoingShoppingAndAskingForPrices.LevelA2Payment emp = new LevelA2.GoingShoppingAndAskingForPrices.LevelA2Payment();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2SickRelative page
    private void LevelA2SickRelative() {
LevelA2.HealthMatters.LevelA2SickRelative emp = new LevelA2.HealthMatters.LevelA2SickRelative();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2VisitingPatient page
    private void LevelA2VisitingPatient() {
LevelA2.HealthMatters.LevelA2VisitingPatient emp = new LevelA2.HealthMatters.LevelA2VisitingPatient();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
 //Takes you to the LevelA2FamilySize page
    private void LevelA2FamilySize() {
LevelA2.SocialisingInACountry.LevelA2FamilySize emp = new LevelA2.SocialisingInACountry.LevelA2FamilySize();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2Hobbies page
    private void LevelA2Hobbies() {
LevelA2.SocialisingInACountry.LevelA2Hobbies emp = new LevelA2.SocialisingInACountry.LevelA2Hobbies();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2ExpiredTicket page
    private void LevelA2ExpiredTicket() {
LevelA2.MakingTravelArrangements.LevelA2ExpiredTicket emp = new LevelA2.MakingTravelArrangements.LevelA2ExpiredTicket();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2AgeRestricted page
    private void LevelA2AgeRestricted() {
LevelA2.ExchangingPersonalInformations.LevelA2AgeRestricted emp = new LevelA2.ExchangingPersonalInformations.LevelA2AgeRestricted();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2Omelette page
    private void LevelA2Omelette() {
LevelA2.CrossCulturalExperiences.LevelA2Omelette emp = new LevelA2.CrossCulturalExperiences.LevelA2Omelette();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }
//Takes you to the LevelA2Weather page
    private void LevelA2Weather() {
LevelA2.Weather.LevelA2Weather emp = new LevelA2.Weather.LevelA2Weather();
       emp.setVisible(true);
       setVisible(false); //Closes This windo
    }

    }